### ISSUE TITLE
brew install OpenResty in MacOs 13 meet err .

### ISSUE THREAD

**Issue by leon0204** [Kong/lua-kong-nginx-module#52]
brew install OpenResty in MacOs 13 meet err . (13.0 (22A380))

WARN: lua-kong-nginx-module source not found, cloning...
Cloning into 'lua-kong-nginx-module'...
fatal: unable to access 'https://github.com/Kong/lua-kong-nginx-module/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by chronolaw** [comment]
It seems not to be related with the repo, I think that we can not do anything for it.
